version: "3.4"

services:
  cuckoo:
    build: ./2.0/
    command: daemon
    cap_add:
      - ALL
    user: root
    privileged: true
    ports:
      - 10.0.0.16:2042:2042
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /cuckoo/storage/:/cuckoo/storage/
      - /rooter:/rooter
      - ./suricata/suricata-cuckoo.yaml:/etc/suricata/suricata-cuckoo.yaml
    network_mode: host
    env_file:
      - ./2.0/config-file.env

  web:
    image: dockercuckoo_cuckoo
    ports:
      - 31337:31337
    links:
      - mongo
      - elasticsearch
      - postgres
    command: web
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /cuckoo/storage/:/cuckoo/storage/
    networks:
      - cuckoo
    env_file:
      - ./2.0/config-file.env

  api:
    depends_on:
      - postgres
    image: dockercuckoo_cuckoo
    ports:
      - 1337:1337
    links:
      - postgres
    command: api
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /cuckoo/storage/:/cuckoo/storage/
    networks:
      - cuckoo
    env_file:
      - ./2.0/config-file.env

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - cuckoo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    container_name: elasticsearch
    environment:
      cluster.name: elasticsearch
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      xpack.ml.enabled: "false"
      xpack.watcher.enabled: "false"
      discovery.type: single-node
      discovery.zen.minimum_master_nodes: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - cuckoo

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.1
    depends_on:
      - elasticsearch
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - cuckoo
    env_file:
      - ./2.0/config-file.env

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cuckoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - cuckoo

networks:
  host:
    driver: default
  cuckoo:
    driver: bridge

volumes:
  es-data:
  postgres-data:
